### PR TITLE
show the current directory in the footer

### PR DESCRIPTION
**Pull request by smason**
I kept getting lost in interactive mode so thought it would be nice to display where the user currently is in the hierarchy

Not sure if this is the right place to add this change, but it seems to do something useful for me.

### CODE REVIEW

**Review by Byron — CHANGES_REQUESTED** [review]
Thanks for your contribution! When reading the intention I thought that this would be something I want to, and when looking at it I noticed something.

Screen Shot 2022-06-10 at 21 10 02

In case it's unclear, the current path is already shown in the top-left and it is displayed in bold.

Under the circumstances, do you think displaying it again in the bottom is worth it?

**Comment by smason** [comment]
ah, just noticed that it's because it's because I'm using "light" theme, so it's effectively invisible for me:

20220610_18h05m27s_grim

not sure what to suggest, maybe using colors differently help fix this and #13?

**Comment by Byron** [comment]
Ah, that makes sense! Maybe you can change the color of the regular path to the one already used for paths elsewhere, that should make it visible and is the simplest solution I can think of.

What do you think?

**Comment by smason** [comment]
just had a chance to play with this and a trivial change to colors looks good to me

20220614_13h01m49s_grim

(forced push because no point actually showing the path twice!)

**Comment by smason** [comment]
thanks!  hopefully my use of `du -s * | sort -rn | head` will start to decrease now

**Pull request merged**
